# Generated by Django 4.0.1 on 2022-01-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_created_at_post_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='represent_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
