# Generated by Django 4.0.1 on 2022-02-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='represent_image',
            field=models.ImageField(blank=True, null=True, upload_to='post/%Y/%m/%d'),
        ),
    ]
